// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/lgangkai/golog"
	"github.com/redis/go-redis/v9"
	"jimoto/account-service/biz"
	"jimoto/account-service/dao"
	"jimoto/account-service/handler"
	"jimoto/account-service/service"
)

// Injectors from wire.go:

func InitAccountHandler(dbMaster *dao.DBMaster, dbSlave *dao.DBSlave, client *redis.Client, logger *golog.Logger) *handler.AccountHandlerImpl {
	userDao := dao.NewUserDao(dbMaster, logger)
	accountService := service.NewAccountService(userDao, logger)
	accountBiz := biz.NewAccountBiz(accountService, logger)
	profileDao := dao.NewProfileDao(dbMaster, dbSlave, client, logger)
	profileService := service.NewProfileService(profileDao, logger)
	profileBiz := biz.NewProfileBiz(profileService, logger)
	accountHandlerImpl := handler.NewAccountHandlerImpl(accountBiz, profileBiz)
	return accountHandlerImpl
}
