// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/lgangkai/golog"
	"github.com/redis/go-redis/v9"
	"jimoto/order-service/biz"
	"jimoto/order-service/dao"
	"jimoto/order-service/handler"
	"jimoto/order-service/service"
)

// Injectors from wire.go:

func InitOrderHandler(dbMaster *dao.DBMaster, dbSlave *dao.DBSlave, client *redis.Client, logger *golog.Logger) *handler.OrderHandlerImpl {
	orderDao := dao.NewOrderDao(dbMaster, dbSlave, logger)
	orderService := service.NewOrderService(orderDao, logger)
	orderBiz := biz.NewOrderBiz(orderService, logger)
	orderHandlerImpl := handler.NewOrderHandlerImpl(orderBiz)
	return orderHandlerImpl
}
